# Generated by Django 5.2.4 on 2025-07-15 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(default='C:\\Users\\kumar\\OneDrive\\Desktop\\SOCIAL MEDIA APP BACKEND\\media\\user.png', upload_to='profile_pics'),
        ),
    ]
